export default ({ spacing, palette, typography }) => ({
  container: {
    margin: 0,
    height: 80,
    width: spacing.fullWidth,
    background: palette.white,
    position: 'relative',
    '&.playing': {
      background: palette.lightGrey['300'],
    },
  },
  thumbnail: {
    position: 'relative',
  },
  img: {
    width: spacing.fullWidth,
    height: spacing.fullHeight,
    display: 'block',
    objectFit: 'cover',
    background: '#FFFFFF',
  },
  duration: {
    position: 'absolute',
    bottom: spacing.baseMargin + 1,
    right: spacing.baseMargin + 1,
    display: 'flex',
    alignItems: 'center',
    borderRadius: 2,
    backgroundColor: palette.lightBlack,
  },
  durationText: {
    ...typography.body2,
    color: palette.white,
    fontSize: '0.625em',
    marginLeft: spacing.smallMargin,
    marginRight: spacing.smallMargin,
  },
  info: {
    padding: spacing.baseMargin,
  },
  name: {
    ...typography.body2,
    fontSize: '0.9em',
    fontWeight: 'bold',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
    overflowX: 'hidden',
    cursor: 'default',
    marginTop: -4,
    color: 'rgba(0, 0, 0, 0.54)',
  },
  warningWrapper: {
    position: 'absolute',
    width: `calc(100% - ${spacing.doubleBaseMargin}px)`,
    height: `calc(100% - ${spacing.doubleBaseMargin}px)`,
    top: spacing.baseMargin,
    left: spacing.baseMargin,
    backgroundColor: palette.lightBlack,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  warningIcon: {
    color: palette.white,
  },
  creator: {
    ...typography.caption,
    position: 'absolute',
    bottom: spacing.baseMargin,
    fontSize: '0.725em',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
  },
  creatorAvatar: {
    marginLeft: spacing.baseMargin,
    width: '1.6em',
    height: '1.6em',
    borderRadius: '50%',
    objectFit: 'cover',
    cursor: 'pointer',
  },
  actions: {
    position: 'absolute',
    right: spacing.baseMargin,
    bottom: spacing.baseMargin,
  },
  disabledAction: {
    color: palette.minBlack,
  },
  actionsWrapper: {
    display: 'flex',
    textAlign: 'center',
    alignSelf: 'center',
  },
  action: {
    fontSize: spacing.baseMargin * 2,
    width: 24,
    height: 24,
  },
  score: {
    ...typography.body2,
    textAlign: 'left',
    margin: 'auto',
    marginLeft: spacing.baseMargin,
    width: spacing.baseMargin * 3,
    fontSize: '0.925em',
    color: palette.secondary['500'],
    '&.active': {
      color: palette.primary['500'],
    },
  },
  scoreRatio: {
    width: '100%',
  },
  favouriteWrapper: {
    cursor: 'pointer',
  },
  favouriteContainer: {
    paddingTop: '0 !important',
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  favouriteBtn: {
    fontSize: spacing.doubleBaseMargin * 1.5,
    width: spacing.doubleBaseMargin * 2,
    height: spacing.doubleBaseMargin * 2,
  },
  progressBar: {
    height: 1,
  },
  loadingContainer: {
    position: 'absolute',
    zIndex: 9,
    background: 'rgba(249,249,249,0.5)',
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  message: {
    position: 'absolute',
    top: 0,
    left: 0,
    color: palette.primary['500'],
  },
  messageTooltip: {
    whiteSpace: 'nowrap',
  },
});
