var events = {};

events.STATION_WAS_CREATED = 'STATION_WAS_CREATED';
events.SET_USER_INFORMATION_SUCCESS = 'SET_USER_INFORMATION_SUCCESS';
events.SET_USER_SCORE_SUCCESS = 'SET_USER_SCORE_SUCCESS';

events.SONG_WAS_ADDED = 'SONG_WAS_ADDED';

module.exports = events;
