export const SERVER_JOINED_STATION_SUCESS = 'SERVER:JOINED_STATION_SUCESS';
export const SERVER_JOINED_STATION_FAILURE = 'SERVER:JOINED_STATION_FAILURE';
export const SERVER_UPDATE_PLAYLIST = 'SERVER:UPDATE_PLAYLIST';
export const SERVER_UPDATE_NOW_PLAYING = 'SERVER:UPDATE_NOW_PLAYING';
export const SERVER_NEW_USER_JOINED = 'SERVER:NEW_USER_JOINED';
export const SERVER_CREATE_STATION_SUCESS = 'SERVER:CREATE_STATION_SUCESS';
export const SERVER_CREATE_STATION_FAILURE = 'SERVER:CREATE_STATION_FAILURE ';

export const CLIENT_JOIN_STATION = 'CLIENT:JOIN_STATION_REQUEST';
export const CLIENT_CREATE_STATION = 'CLIENT:CREATE_STATION_REQUEST';
export const CLIENT_UPVOTE_VIDEO = 'CLIENT:UPVOTE_VIDEO_REQUEST';
export const CLIENT_UN_UPVOTE_VIDEO = 'CLIENT:UN_UPVOTE_VIDEO_REQUEST';
export const CLIENT_ADD_LINK_VIDEO = 'CLIENT:ADD_LINK_VIDEO_REQUEST';