// SERVER RESPONSES
export const SERVER_JOINED_STATION_SUCCESS = 'SERVER:JOINED_STATION_SUCCESS';
export const SERVER_JOINED_STATION_FAILURE = 'SERVER:JOINED_STATION_FAILURE';
export const SERVER_LEFT_STATION_SUCCESS = 'SERVER:LEFT_STATION_SUCCESS';
export const SERVER_LEFT_STATION_FAILURE = 'SERVER:LEFT_STATION_FAILURE';
export const SERVER_CREATE_STATION_SUCCESS = 'SERVER:CREATE_STATION_SUCCESS';
export const SERVER_CREATE_STATION_FAILURE = 'SERVER:CREATE_STATION_FAILURE ';

// SERVER NOTIFY
export const SERVER_UPDATE_PLAYLIST = 'SERVER:UPDATE_PLAYLIST';
export const SERVER_UPDATE_NOW_PLAYING = 'SERVER:UPDATE_NOW_PLAYING';
export const SERVER_NEW_USER_JOINED = 'SERVER:NEW_USER_JOINED';
export const SERVER_USER_LEFT = 'SERVER:USER_LEFT';

// CLIENT REQUESTS
export const CLIENT_JOIN_STATION = 'CLIENT:JOIN_STATION_REQUEST';
export const CLIENT_LEAVE_STATION = 'CLIENT:LEAVE_STATION_REQUEST';
export const CLIENT_CREATE_STATION = 'CLIENT:CREATE_STATION_REQUEST';
export const CLIENT_UPVOTE_VIDEO = 'CLIENT:UPVOTE_VIDEO_REQUEST';
export const CLIENT_DOWNVOTE_VIDEO = 'CLIENT:DOWNVOTE_VIDEO_REQUEST';
export const CLIENT_ADD_LINK_VIDEO = 'CLIENT:ADD_LINK_VIDEO_REQUEST';
