import { createMuiTheme } from 'material-ui/styles';
import {
  jellyBean,
  sunray,
  pearl,
  mummyTomb,
  richBlack,
  white,
  black,
  transparent,
  fullBlack,
  darkBlack,
  lightBlack,
  minBlack,
  faintBlack,
  fullWhite,
  darkWhite,
  lightWhite,
} from './Color';

export default createMuiTheme({
  palette: {
    primary: jellyBean,
    secondary: richBlack,
    red: jellyBean,
    yellow: sunray,
    lightGrey: pearl,
    green: mummyTomb,
    darkGreen: richBlack,
    white,
    black,
    transparent,
    fullBlack,
    darkBlack,
    lightBlack,
    minBlack,
    faintBlack,
    fullWhite,
    darkWhite,
    lightWhite,
  },
  typography: {
    fontFamily: `'Roboto Slab', sans-serif`,
  },
  spacing: {
    smallMargin: 4,
    baseMargin: 8,
    doubleBaseMargin: 16,
    fullWidth: '100%',
    fullHeight: '100%',
    fullViewportWidth: '100vw',
    fullViewportHeight: '100vh',
  },
});
